# Generated by Django 5.2 on 2026-04-21 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма договора')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работ')),
                ('description', models.TextField(blank=True, verbose_name='Описание договора')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО директора')),
                ('director_position', models.CharField(default='Генеральный директор', max_length=255, verbose_name='Должность директора')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование банка')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счет')),
                ('checking_account', models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код объекта')),
                ('address', models.TextField(blank=True, verbose_name='Адрес объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Объект строительства',
                'verbose_name_plural': 'Объекты строительства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование вида работ')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код вида работ')),
                ('unit', models.CharField(default='м3', max_length=50, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер акта')),
                ('date', models.DateField(verbose_name='Дата акта')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Период с')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Период по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('approved', 'Подписан'), ('paid', 'Оплачен'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая сумма')),
                ('nds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='В том числе НДС')),
                ('nds_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Ставка НДС (%)')),
                ('without_nds', models.BooleanField(default=False, verbose_name='Без НДС')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='acts.contract', verbose_name='Договор')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='acts.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Акт КС-2',
                'verbose_name_plural': 'Акты КС-2',
                'ordering': ['-date', '-number'],
                'unique_together': {('number', 'contract')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='acts.contractor', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='acts.object', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='ActItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='№ п/п')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование работ')),
                ('unit', models.CharField(default='м3', max_length=50, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена за ед.')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='acts.act', verbose_name='Акт')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acts.worktype', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Строка акта',
                'verbose_name_plural': 'Строки актов',
                'ordering': ['number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('number', 'contractor')},
        ),
    ]
